modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="advanced_combat"
version="1.0.0"
displayName="Advanced Combat"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Warren, MCreator"

[[dependencies.advanced_combat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




